syms vTdot vT psi alfaT psidot alfaTdot FxF FxR FyF FyR delta DELTA DELTAdot ...
    m gamma GAMMA GAMMAdot OMEGA OMEGAdot xdotdot ydotdot FN g VDOT ALFADOT

%eqs = [
%        m*xdotdot == FxR*cos(GAMMA)*cos(psi) - FyR*cos(OMEGA)*sin(psi) ...
%        + FxF*cos(delta)*cos(GAMMA)*cos(psi) - FxF*sin(delta)*cos(OMEGA)*sin(psi) ...
%        - FyF*sin(delta)*cos(GAMMA)*cos(psi) - FyF*cos(delta)*cos(OMEGA)*sin(psi) ...
%        -FN*sin(gamma)*cos(DELTA), ...
%        m*ydotdot == FxR*cos(GAMMA)*sin(psi) + FyR*cos(OMEGA)*cos(psi) + ...
%        FxF*cos(delta)*cos(GAMMA)*sin(psi) + FxF*sin(delta)*cos(OMEGA)*cos(psi) - ...
%        FyF*sin(delta)*cos(GAMMA)*sin(psi) + FyF*cos(delta)*cos(OMEGA)*cos(psi) + ...
%        FN*sin(gamma)*sin(DELTA), ...
%        FN == m*g*cos(gamma), ...
%        GAMMAdot == psidot*gamma*sin(DELTA + pi/2 - psi), ...
%        OMEGAdot == -psidot*gamma*cos(DELTA + pi/2 - psi), ...
%        xdotdot == vdot*cos(alfaT)*cos(GAMMA)*cos(psi) - v*sin(alfaT)*cos(GAMMA)*cos(psi)*alfaTdot ...
%        - v*cos(alfaT)*sin(GAMMA)*cos(psi)*GAMMAdot - v*cos(alfaT)*cos(GAMMA)*sin(psi)*psidot ...
%        - vdot*sin(alfaT)*cos(OMEGA)*sin(psi) - v*cos(alfaT)*cos(OMEGA)*sin(psi)*alfaTdot ...
%        + v*sin(alfaT)*sin(OMEGA)*sin(psi)*OMEGAdot - v*sin(alfaT)*cos(OMEGA)*cos(psi)*psidot, ...
%        ydotdot == vdot*cos(alfaT)*cos(GAMMA)*sin(psi) - alfaTdot*v*sin(alfaT)*cos(GAMMA)*sin(psi) - ...
%        GAMMAdot*v*cos(alfaT)*sin(GAMMA)*sin(psi) + psidot*v*cos(alfaT)*cos(GAMMA)*cos(psi) + ...
%        vdot*sin(alfaT)*cos(OMEGA)*cos(psi) + alfaTdot*v*cos(alfaT)*cos(OMEGA)*cos(psi) - ...
%        OMEGAdot*v*sin(alfaT)*sin(OMEGA)*cos(psi) - psidot*v*sin(alfaT)*cos(OMEGA)*sin(psi), ...
%        GAMMA == gamma*cos(DELTA + pi/2 - psi), ...
%        OMEGA == gamma*sin(DELTA + pi/2 - psi)
%        ];
   

%eqs = [
%    m*vdot*cos(alfaT)*cos(GAMMA)*cos(psi) - v*sin(alfaT)*cos(GAMMA)*cos(psi)*alfaTdot ...
%        - v*cos(alfaT)*sin(GAMMA)*cos(psi)*GAMMAdot - v*cos(alfaT)*cos(GAMMA)*sin(psi)*psidot ...
%        - vdot*sin(alfaT)*cos(OMEGA)*sin(psi) - v*cos(alfaT)*cos(OMEGA)*sin(psi)*alfaTdot ...
%        + v*sin(alfaT)*sin(OMEGA)*sin(psi)*OMEGAdot - v*sin(alfaT)*cos(OMEGA)*cos(psi)*psidot == FxR*cos(GAMMA)*cos(psi) - FyR*cos(OMEGA)*sin(psi) ...
%        + FxF*cos(delta)*cos(GAMMA)*cos(psi) - FxF*sin(delta)*cos(OMEGA)*sin(psi) ...
%        - FyF*sin(delta)*cos(GAMMA)*cos(psi) - FyF*cos(delta)*cos(OMEGA)*sin(psi) - FN*sin(gamma)*cos(DELTA), ...
%    m*vdot*cos(alfaT)*cos(GAMMA)*sin(psi) - alfaTdot*v*sin(alfaT)*cos(GAMMA)*sin(psi) - ...
%        GAMMAdot*v*cos(alfaT)*sin(GAMMA)*sin(psi) + psidot*v*cos(alfaT)*cos(GAMMA)*cos(psi) + ...
%        vdot*sin(alfaT)*cos(OMEGA)*cos(psi) + alfaTdot*v*cos(alfaT)*cos(OMEGA)*cos(psi) - ...
%        OMEGAdot*v*sin(alfaT)*sin(OMEGA)*cos(psi) - psidot*v*sin(alfaT)*cos(OMEGA)*sin(psi) == FxR*cos(GAMMA)*sin(psi) + FyR*cos(OMEGA)*cos(psi) + ...
%        FxF*cos(delta)*cos(GAMMA)*sin(psi) + FxF*sin(delta)*cos(OMEGA)*cos(psi) - ...
%        FyF*sin(delta)*cos(GAMMA)*sin(psi) + FyF*cos(delta)*cos(OMEGA)*cos(psi) + FN*sin(gamma)*sin(DELTA)
%];

eqs = [
    m*vTdot*cos(alfaT)*cos(GAMMA)*cos(psi) - vT*sin(alfaT)*cos(GAMMA)*cos(psi)*alfaTdot ...
        - vT*cos(alfaT)*sin(GAMMA)*cos(psi)*GAMMAdot - vT*cos(alfaT)*cos(GAMMA)*sin(psi)*psidot ...
        - vTdot*sin(alfaT)*cos(OMEGA)*sin(psi) - vT*cos(alfaT)*cos(OMEGA)*sin(psi)*alfaTdot ...
        + vT*sin(alfaT)*sin(OMEGA)*sin(psi)*OMEGAdot - vT*sin(alfaT)*cos(OMEGA)*cos(psi)*psidot == FxR*cos(GAMMA)*cos(psi) - FyR*cos(OMEGA)*sin(psi) ...
        + FxF*cos(delta)*cos(GAMMA)*cos(psi) - FxF*sin(delta)*cos(OMEGA)*sin(psi) ...
        - FyF*sin(delta)*cos(GAMMA)*cos(psi) - FyF*cos(delta)*cos(OMEGA)*sin(psi) - m*g*cos(gamma)*sin(gamma)*cos(DELTA), ...
    m*vTdot*cos(alfaT)*cos(GAMMA)*sin(psi) - vT*sin(alfaT)*cos(GAMMA)*sin(psi)*alfaTdot - ...
        vT*cos(alfaT)*sin(GAMMA)*sin(psi)*GAMMAdot + vT*cos(alfaT)*cos(GAMMA)*cos(psi)*psidot + ...
        vTdot*sin(alfaT)*cos(OMEGA)*cos(psi) + vT*cos(alfaT)*cos(OMEGA)*cos(psi)*alfaTdot - ...
        vT*sin(alfaT)*sin(OMEGA)*cos(psi)*OMEGAdot - vT*sin(alfaT)*cos(OMEGA)*sin(psi)*psidot == FxR*cos(GAMMA)*sin(psi) + FyR*cos(OMEGA)*cos(psi) + ...
        FxF*cos(delta)*cos(GAMMA)*sin(psi) + FxF*sin(delta)*cos(OMEGA)*cos(psi) - ...
        FyF*sin(delta)*cos(GAMMA)*sin(psi) + FyF*cos(delta)*cos(OMEGA)*cos(psi) + m*g*cos(gamma)*sin(gamma)*sin(DELTA)
];

S = solve(eqs, [vTdot alfaTdot]);

%S.vdot
VTDOT = simplify(S.vTdot)

%S.alfaTdot
ALFADOT = simplify(S.alfaTdot)

   
%GAMMA = gamma*cos(DELTA + pi/2 - psi)
%GAMMAdot = psidot*gamma*sin*(DELTA + pi/2 - psi) - DELTAdot sin(DELTA + pi/2 - psi)

%OMEGA = gamma*sin(DELTA + pi/2 - psi)
%OMEGAdot = -psidot*gamma*cos(DELTA + pi/2 - psi) + DELTAdot cos(DELTA + pi/2 - psi)